#!/bin/bash

DEVICE_PATH="/dev/ttyACM0"  # Jackal Serial
USER="tomatoxplorers"

while true; do
    if [ -e "$DEVICE_PATH" ]; then
        echo "Device detected at $(date)"
        break
    fi
    sleep 5  # Check every 5 seconds
done

source /opt/ros/humble/setup.bash

ros2 launch jackal_control_humble jackal_control.launch.py

echo "DONE"
